Repository PrestaShop/productcomments, pull requests merged in 2020-12, with the labels that each got.

#85 Fix phpstan configuration
  .github/workflows/php.yml
Labels: bug

#77 Fix: Product grade update after product page being updated
  views/js/list-comments.js
Labels: QA ✔️, bug

#78 Redirect after noabuseComment submit to prevent resubmit on page reload
  productcomments.php
Labels: QA ✔️, bug

#90 Use the correct version of php-cs-fixer
  .github/workflows/php.yml
Labels: bug

#89 Fixing the bug that appeared when anonymize customer last name option has been added.
  controllers/front/ListComments.php
Labels: QA ✔️
