Repository PrestaShop/productcomments, pull requests merged in 2021-09, with the labels that each got.

#96 Infinite ajax loop with undefined IDs
  views/js/productListingComments.js
Labels: bug

#111 Hook on filterProductContent for adding ProductComments data
  productcomments.php
  upgrade/install-5.0.0.php
Labels: QA ✔️

#112 Removed Rich Snippet Rating
  views/templates/hook/product-additional-info.tpl
Labels: bug, QA ✔️
