Repository PrestaShop/productcomments, pull requests merged in 2022-01, with the labels that each got.

#128 Improved Workflow Build Release
  .github/workflows/build-release.yml
Labels: enhancement

#125 To prevent google from indexing the icon names use data-icon and css to show the icons
  views/css/productcomments.css
  views/js/list-comments.js
  views/templates/hook/alert-modal.tpl
  views/templates/hook/confirm-modal.tpl
  views/templates/hook/empty-product-comment.tpl
  views/templates/hook/product-additional-info.tpl
  views/templates/hook/product-comment-item-prototype.tpl
  views/templates/hook/product-comments-list.tpl
Labels: QA ✔️

#107 Fix upgrade module to v4
  src/Repository/ProductCommentRepository.php
  upgrade/install-4.0.0.php
Labels: bug, QA ✔️
